import { useMemo, useState, type FormEvent } from "react";
import { useMutation } from "@tanstack/react-query";
import { api, ApiError } from "@/api/client";
import type { AdminAgent, AdminConnection, AdminKnowledge, AdminUser, AdminWorkspace } from "./types";

function errorText(error: unknown) { return error instanceof ApiError ? error.message : "No se pudo completar la operación."; }
function isTrue(value: boolean | number) { return value !== false && value !== 0; }
function fmt(value: number) { return value >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : value >= 1_000 ? `${(value / 1_000).toFixed(1)}K` : String(value); }
function date(value?: string) { if (!value) return "—"; const parsed = new Date(value); return Number.isNaN(parsed.valueOf()) ? "—" : parsed.toLocaleDateString("es-ES"); }

export function AdminUsersPanel({ users, allowCreate, onReload }: { users: AdminUser[]; allowCreate: boolean; onReload: () => void }) {
  const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [active, setActive] = useState(""); const [verified, setVerified] = useState("");
  const [editor, setEditor] = useState<{ mode: "create"; user?: never } | { mode: "edit"; user: AdminUser } | null>(null);
  const action = useMutation({
    mutationFn: async (task: { kind: "active"; user: AdminUser } | { kind: "admin"; user: AdminUser } | { kind: "delete"; user: AdminUser }) => {
      const url = `/api/admin/users/${encodeURIComponent(task.user.username)}`;
      if (task.kind === "delete") return api.delete(url);
      if (task.kind === "admin") return api.patch(url, { role: "admin" });
      return api.patch(url, { is_active: !isTrue(task.user.is_active) });
    },
    onSuccess: onReload,
  });
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return users.filter((user) => (!q || `${user.email ?? ""} ${user.username}`.toLowerCase().includes(q)) && (!role || user.role === role) && (!active || isTrue(user.is_active) === (active === "true")) && (!verified || isTrue(user.is_verified) === (verified === "true"))).sort((a, b) => (b.created_at ?? "").localeCompare(a.created_at ?? "")); }, [users, search, role, active, verified]);
  return <><div className="admin-toolbar"><div className="admin-search-wrap"><span className="search-icon">⌕</span><input className="admin-search" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por email…" /></div><select className="admin-select" value={role} onChange={(event) => setRole(event.target.value)}><option value="">Todos los roles</option><option value="admin">Admin</option><option value="gestor">Gestor</option><option value="standard">Estándar</option></select><select className="admin-select" value={active} onChange={(event) => setActive(event.target.value)}><option value="">Cualquier estado</option><option value="true">Activos</option><option value="false">Bloqueados</option></select><select className="admin-select" value={verified} onChange={(event) => setVerified(event.target.value)}><option value="">Verificación</option><option value="true">Verificados</option><option value="false">Sin verificar</option></select>{allowCreate && <button className="btn btn-primary btn-sm" style={{ marginLeft: "auto" }} onClick={() => setEditor({ mode: "create" })}>+ Nuevo usuario</button>}</div>
    {action.error && <p className="form-error">{errorText(action.error)}</p>}{filtered.length ? <table className="admin-table"><thead><tr><th>Email</th><th>Rol</th><th>Estado</th><th>Verificado</th><th>Tokens</th><th>Creado</th><th /></tr></thead><tbody>{filtered.map((user) => <tr key={user.username}><td><div className="user-avatar-cell"><span className="user-avatar-sm">{(user.email || user.username).charAt(0).toUpperCase()}</span><span>{user.email || user.username}</span></div></td><td><span className={`badge ${user.role === "admin" ? "badge--admin" : "badge--std"}`}>{user.role}</span></td><td><span className={`badge ${isTrue(user.is_active) ? "badge--ok" : "badge--danger"}`}>{isTrue(user.is_active) ? "Activo" : "Bloqueado"}</span></td><td><span className={`badge ${isTrue(user.is_verified) ? "badge--ok" : "badge--warn"}`}>{isTrue(user.is_verified) ? "Verificado" : "Sin verificar"}</span></td><td className="td-tokens">{fmt((user.tokens_in ?? 0) + (user.tokens_out ?? 0))}</td><td className="td-date">{date(user.created_at)}</td><td className="td-actions"><div style={{ display: "flex", gap: 4, justifyContent: "flex-end" }}><button className="btn btn-ghost btn-sm" onClick={() => setEditor({ mode: "edit", user })}>Editar</button><button className="btn btn-ghost btn-sm" disabled={action.isPending} onClick={() => action.mutate({ kind: "active", user })}>{isTrue(user.is_active) ? "Bloquear" : "Activar"}</button>{user.role !== "admin" && <button className="btn btn-ghost btn-sm" disabled={action.isPending} onClick={() => { if (confirm(`¿Promover a ${user.username} a administrador?`)) action.mutate({ kind: "admin", user }); }}>Hacer admin</button>}<button className="btn btn-ghost btn-sm action-item--danger" disabled={action.isPending} onClick={() => { if (confirm(`¿Eliminar permanentemente a ${user.username}?`)) action.mutate({ kind: "delete", user }); }}>Eliminar</button></div></td></tr>)}</tbody></table> : <div className="admin-empty">No hay usuarios que coincidan con los filtros.</div>}
    {editor && <UserEditor state={editor} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); onReload(); }} />}
  </>;
}

function UserEditor({ state, onClose, onSaved }: { state: { mode: "create"; user?: never } | { mode: "edit"; user: AdminUser }; onClose: () => void; onSaved: () => void }) {
  const [email, setEmail] = useState(state.mode === "edit" ? state.user.email ?? state.user.username : ""); const [displayName, setDisplayName] = useState(state.mode === "edit" ? state.user.display_name ?? "" : ""); const [role, setRole] = useState(state.mode === "edit" ? state.user.role : "standard"); const [active, setActive] = useState(state.mode === "edit" ? isTrue(state.user.is_active) : true); const [password, setPassword] = useState("");
  const save = useMutation({ mutationFn: () => state.mode === "create" ? api.post("/api/admin/users", { email: email.trim(), display_name: displayName.trim() || undefined, role, password }) : api.patch(`/api/admin/users/${encodeURIComponent(state.user.username)}`, { role, is_active: active, ...(password ? { password } : {}) }), onSuccess: onSaved });
  return <div className="modal-bg" role="dialog" aria-modal="true" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="modal-box" style={{ maxWidth: 480 }}><div className="modal-header"><h3 className="modal-title">{state.mode === "create" ? "Nuevo usuario" : "Editar usuario"}</h3><button className="modal-close" onClick={onClose}>×</button></div><form onSubmit={(event) => { event.preventDefault(); if (email.trim() && (state.mode === "edit" || password.length >= 8)) save.mutate(); }}><div className="modal-body"><div className="field"><label>Email</label><input className="input" type="email" required disabled={state.mode === "edit"} value={email} onChange={(event) => setEmail(event.target.value)} /></div>{state.mode === "create" && <div className="field"><label>Nombre visible</label><input className="input" value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></div>}<div className="field"><label>Rol</label><select className="select" value={role} onChange={(event) => setRole(event.target.value)}><option value="standard">Estándar</option><option value="gestor">Gestor</option><option value="admin">Administrador</option></select></div>{state.mode === "edit" && <label className="toggle"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /><span className="toggle-track" /><span className="toggle-label">Activo</span></label>}<div className="field"><label>{state.mode === "create" ? "Contraseña" : "Nueva contraseña (opcional)"}</label><input className="input" type="password" minLength={8} required={state.mode === "create"} value={password} onChange={(event) => setPassword(event.target.value)} /></div>{save.error && <p className="form-error">{errorText(save.error)}</p>}</div><div className="modal-footer"><button type="button" className="btn btn-ghost" onClick={onClose}>Cancelar</button><button className="btn btn-primary" disabled={save.isPending}>{save.isPending ? "Guardando…" : state.mode === "create" ? "Crear usuario" : "Guardar"}</button></div></form></div></div>;
}

export function AdminWorkspacesPanel({ workspaces, onReload }: { workspaces: AdminWorkspace[]; onReload: () => void }) {
  const [search, setSearch] = useState("");
  const action = useMutation({ mutationFn: ({ workspace, kind }: { workspace: AdminWorkspace; kind: "status" | "delete" }) => kind === "delete" ? api.delete(`/api/admin/workspaces/${encodeURIComponent(workspace.id)}`) : api.post(`/api/admin/workspaces/${encodeURIComponent(workspace.id)}/status`, { status: workspace.status === "disabled" ? "active" : "disabled" }), onSuccess: onReload });
  const filtered = useMemo(() => { const q = search.toLowerCase(); return workspaces.filter((workspace) => !q || `${workspace.name} ${workspace.created_by}`.toLowerCase().includes(q)); }, [search, workspaces]);
  return <><div className="admin-toolbar"><input className="admin-search" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nombre o creador…" /></div>{action.error && <p className="form-error">{errorText(action.error)}</p>}{filtered.length ? <table className="admin-table"><thead><tr><th>Nombre</th><th>Creador</th><th>Miembros</th><th>Agentes</th><th>Conexiones</th><th>Conocimiento</th><th>Tokens</th><th>Estado</th><th /></tr></thead><tbody>{filtered.map((workspace) => <tr key={workspace.id}><td><span className="conn-name">{workspace.name}</span></td><td className="td-owner">{workspace.created_by}</td><td>{workspace.member_count ?? 0}</td><td>{workspace.agents_count ?? 0}</td><td>{workspace.connections_count ?? 0}</td><td>{workspace.knowledge_count ?? 0}</td><td className="td-tokens">{fmt((workspace.tokens_in ?? 0) + (workspace.tokens_out ?? 0))}</td><td><span className={`badge ${workspace.status === "disabled" ? "badge--danger" : "badge--ok"}`}>{workspace.status === "disabled" ? "Desactivado" : "Activo"}</span></td><td className="td-actions"><button className="btn btn-ghost btn-sm" disabled={action.isPending} onClick={() => action.mutate({ workspace, kind: "status" })}>{workspace.status === "disabled" ? "Reactivar" : "Desactivar"}</button><button className="btn btn-ghost btn-sm action-item--danger" disabled={action.isPending} onClick={() => { if (confirm(`¿Eliminar "${workspace.name}" y todo su contenido?`)) action.mutate({ workspace, kind: "delete" }); }}>Eliminar</button></td></tr>)}</tbody></table> : <div className="admin-empty">No hay grupos de trabajo.</div>}</>;
}

export function AdminAgentsPanel({ agents, onReload }: { agents: AdminAgent[]; onReload: () => void }) {
  const [search, setSearch] = useState(""); const [owner, setOwner] = useState(""); const [editing, setEditing] = useState<AdminAgent | null>(null);
  const owners = useMemo(() => [...new Set(agents.map((agent) => agent.owner_email || agent.owner_id).filter((value): value is string => Boolean(value)))].sort(), [agents]);
  const filtered = useMemo(() => { const q = search.toLowerCase(); return agents.filter((agent) => (!q || `${agent.name ?? agent.id} ${agent.model ?? ""}`.toLowerCase().includes(q)) && (!owner || (agent.owner_email || agent.owner_id) === owner)); }, [agents, search, owner]);
  const remove = useMutation({ mutationFn: (agent: AdminAgent) => api.delete(`/api/admin/agents/${encodeURIComponent(agent.id)}?scope=${encodeURIComponent(agent.scope ?? "private")}`), onSuccess: onReload });
  return <><div className="admin-toolbar"><input className="admin-search" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar agente…" /><select className="admin-select" value={owner} onChange={(event) => setOwner(event.target.value)}><option value="">Todos los propietarios</option>{owners.map((value) => <option key={value}>{value}</option>)}</select></div>{remove.error && <p className="form-error">{errorText(remove.error)}</p>}{filtered.length ? <table className="admin-table"><thead><tr><th>Agente</th><th>Tipo</th><th>Modelo</th><th>Propietario</th><th>Visibilidad</th><th>Tokens</th><th /></tr></thead><tbody>{filtered.map((agent) => <tr key={`${agent.scope}-${agent.id}`}><td><span className="conn-name">{agent.name || agent.id}</span></td><td><span className="badge badge--type">{agent.agent_type || "generic"}</span></td><td>{agent.model || "—"}</td><td className="td-owner">{agent.owner_email || agent.owner_id || "—"}</td><td><span className={`badge ${agent.scope === "public" ? "badge--ok" : "badge--std"}`}>{agent.scope || "private"}</span></td><td className="td-tokens">{fmt((agent.tokens_in ?? 0) + (agent.tokens_out ?? 0))}</td><td className="td-actions"><button className="btn btn-ghost btn-sm" onClick={() => setEditing(agent)}>Editar</button><button className="btn btn-ghost btn-sm action-item--danger" disabled={remove.isPending} onClick={() => { if (confirm(`¿Eliminar el agente "${agent.name || agent.id}"?`)) remove.mutate(agent); }}>Eliminar</button></td></tr>)}</tbody></table> : <div className="admin-empty">No hay agentes.</div>}{editing && <AgentEditor agent={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); onReload(); }} />}</>;
}

function AgentEditor({ agent, onClose, onSaved }: { agent: AdminAgent; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(agent.name ?? agent.id); const [type, setType] = useState(agent.agent_type ?? "generic"); const [model, setModel] = useState(agent.model ?? ""); const [connection, setConnection] = useState(agent.connection_id ?? ""); const [temperature, setTemperature] = useState(agent.temperature ?? 0.7); const [prompt, setPrompt] = useState(agent.system_prompt ?? "");
  const save = useMutation({ mutationFn: () => api.put(`/api/admin/agents/${encodeURIComponent(agent.id)}`, { name: name.trim(), agent_type: type, model: model.trim(), connection_id: connection.trim() || null, temperature, system_prompt: prompt }), onSuccess: onSaved });
  const submit = (event: FormEvent) => { event.preventDefault(); if (name.trim()) save.mutate(); };
  return <div className="modal-bg" role="dialog" aria-modal="true"><div className="modal-box" style={{ maxWidth: 540 }}><div className="modal-header"><h3 className="modal-title">Editar agente</h3><button className="modal-close" onClick={onClose}>×</button></div><form onSubmit={submit}><div className="modal-body"><div className="field"><label>Nombre</label><input className="input" required value={name} onChange={(event) => setName(event.target.value)} /></div><div className="field"><label>Tipo</label><select className="select" value={type} onChange={(event) => setType(event.target.value)}><option value="generic">Genérico</option><option value="claude">Claude</option><option value="openai">OpenAI</option><option value="github">GitHub</option></select></div><div className="field"><label>Modelo</label><input className="input" value={model} onChange={(event) => setModel(event.target.value)} /></div><div className="field"><label>Conexión</label><input className="input" value={connection} onChange={(event) => setConnection(event.target.value)} /></div><div className="field"><label>Temperatura</label><input className="input" type="number" min={0} max={2} step={0.05} value={temperature} onChange={(event) => setTemperature(Number(event.target.value))} /></div><div className="field"><label>Prompt del sistema</label><textarea className="input" rows={6} value={prompt} onChange={(event) => setPrompt(event.target.value)} /></div>{save.error && <p className="form-error">{errorText(save.error)}</p>}</div><div className="modal-footer"><button type="button" className="btn btn-ghost" onClick={onClose}>Cancelar</button><button className="btn btn-primary" disabled={save.isPending}>{save.isPending ? "Guardando…" : "Guardar"}</button></div></form></div></div>;
}

export function AdminConnectionsPanel({ connections, onReload }: { connections: AdminConnection[]; onReload: () => void }) {
  const [owner, setOwner] = useState(""); const owners = useMemo(() => [...new Set(connections.map((connection) => connection.owner_email || connection.owner_id).filter((value): value is string => Boolean(value)))].sort(), [connections]); const filtered = connections.filter((connection) => !owner || (connection.owner_email || connection.owner_id) === owner); const remove = useMutation({ mutationFn: (id: string) => api.delete(`/api/admin/connections/${encodeURIComponent(id)}`), onSuccess: onReload });
  return <><div className="admin-toolbar"><select className="admin-select" value={owner} onChange={(event) => setOwner(event.target.value)}><option value="">Todos los propietarios</option>{owners.map((value) => <option key={value}>{value}</option>)}</select></div>{remove.error && <p className="form-error">{errorText(remove.error)}</p>}{filtered.length ? <table className="admin-table"><thead><tr><th>Nombre</th><th>Tipo</th><th>Propietario</th><th>Tokens</th><th>Creado</th><th /></tr></thead><tbody>{filtered.map((connection) => <tr key={connection.id}><td><span className="conn-name">{connection.name || connection.id}</span></td><td><span className="badge badge--type">{connection.type || "—"}</span></td><td className="td-owner">{connection.owner_email || connection.owner_id || "—"}</td><td className="td-tokens">{fmt((connection.tokens_in ?? 0) + (connection.tokens_out ?? 0))}</td><td className="td-date">{date(connection.created_at)}</td><td className="td-actions"><button className="btn btn-ghost btn-sm action-item--danger" disabled={remove.isPending} onClick={() => { if (confirm("¿Eliminar esta conexión y su historial de tokens?")) remove.mutate(connection.id); }}>Eliminar</button></td></tr>)}</tbody></table> : <div className="admin-empty">No hay conexiones registradas.</div>}</>;
}

export function AdminKnowledgePanel({ items, onReload }: { items: AdminKnowledge[]; onReload: () => void }) {
  const [search, setSearch] = useState(""); const [type, setType] = useState(""); const [owner, setOwner] = useState(""); const owners = useMemo(() => [...new Set(items.map((item) => item.owner_email || item.owner_id).filter((value): value is string => Boolean(value)))].sort(), [items]); const filtered = useMemo(() => { const q = search.toLowerCase(); return items.filter((item) => (!q || `${item.title ?? item.id} ${item.owner_email ?? item.owner_id ?? ""}`.toLowerCase().includes(q)) && (!type || item.type === type) && (!owner || (item.owner_email || item.owner_id) === owner)); }, [items, owner, search, type]); const remove = useMutation({ mutationFn: (id: string) => api.delete(`/api/admin/knowledge/${encodeURIComponent(id)}`), onSuccess: onReload });
  return <><div className="admin-toolbar"><input className="admin-search" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por título o propietario…" /><select className="admin-select" value={type} onChange={(event) => setType(event.target.value)}><option value="">Todos los tipos</option><option value="url">URL</option><option value="document">Documento</option></select><select className="admin-select" value={owner} onChange={(event) => setOwner(event.target.value)}><option value="">Todos los propietarios</option>{owners.map((value) => <option key={value}>{value}</option>)}</select></div>{remove.error && <p className="form-error">{errorText(remove.error)}</p>}{filtered.length ? <table className="admin-table"><thead><tr><th>Título</th><th>Tipo</th><th>Propietario</th><th>Caracteres</th><th>Creado</th><th /></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><span className="conn-name">{item.title || item.id}</span></td><td><span className={`badge ${item.type === "url" ? "badge--ok" : "badge--type"}`}>{item.type === "url" ? "URL" : "Doc"}</span></td><td className="td-owner">{item.owner_email || item.owner_id || "—"}</td><td className="td-tokens">{(item.char_count ?? 0).toLocaleString("es-ES")}</td><td className="td-date">{date(item.created_at)}</td><td className="td-actions"><button className="btn btn-ghost btn-sm action-item--danger" disabled={remove.isPending} onClick={() => { if (confirm("¿Eliminar este elemento de conocimiento?")) remove.mutate(item.id); }}>Eliminar</button></td></tr>)}</tbody></table> : <div className="admin-empty">No hay elementos de conocimiento.</div>}</>;
}
