import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api, ApiError, streamEvents } from "@/api/client";
import "@/styles/routes/admin/admin.css";
import "@/styles/routes/admin/centinel/centinel.css";
import "@/styles/routes/admin/centinel/centinel-stress.css";

interface TestFile { file: string; tests: string[]; count: number }
interface TestDirectory { dir: string; files: TestFile[]; count: number }
interface TestTree { dirs: TestDirectory[] }
interface TestSummary { passed?: number; failed?: number; error?: number; skipped?: number; warning?: number; duration_s?: number }
interface RunnerStatus { status: "idle" | "running" | "done" | "aborted" | "error"; run_id?: string | null; target?: string | null; started_at?: number | null; finished_at?: number | null; summary?: TestSummary; failed_ids?: string[] }
interface TestEvent { type: "started" | "collecting" | "test" | "summary" | "done" | "aborted" | "error"; run_id?: string; target?: string; count?: number; file?: string; name?: string; status?: "passed" | "failed" | "error" | "skipped"; progress?: number; traceback?: string | null; failed_ids?: string[]; exit_code?: number; message?: string; passed?: number; failed?: number; skipped?: number; duration_s?: number }
type CompletedTestEvent = TestEvent & { type: "test"; file: string; name: string; status: "passed" | "failed" | "error" | "skipped" };
interface HistoryItem { run_id: string; target: string; started_at?: number; finished_at?: number; status: string; summary?: TestSummary }

function errorText(error: unknown) { return error instanceof ApiError ? error.message : "No se pudo completar la operación."; }

export function CentinelPage() {
  const [section, setSection] = useState<"functional" | "stress">("functional");
  return <main className="page-content centinel-page"><div className="page-header"><div><h1 className="page-title"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" style={{ verticalAlign: -3, marginRight: 8 }}><path d="M12 2L3 7v5c0 5.25 3.75 10.15 9 11.35C17.25 22.15 21 17.25 21 12V7L12 2z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/><path d="M9 12l2 2 4-4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>Centinel</h1><p className="page-subtitle">{section === "functional" ? "Test runner del backend" : "Pruebas de rendimiento"}</p></div><div className="ctn-section-tabs"><button className={`ctn-section-tab${section === "functional" ? " active" : ""}`} onClick={() => setSection("functional")}><svg width="13" height="13" viewBox="0 0 16 16" fill="none"><path d="M3 8l3.5 4L13 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>Funcionalidad</button><button className={`ctn-section-tab${section === "stress" ? " active" : ""}`} onClick={() => setSection("stress")}><svg width="13" height="13" viewBox="0 0 16 16" fill="none"><path d="M2 12l3-6 3 4 2-3 4 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>Rendimiento</button></div></div>{section === "functional" ? <FunctionalRunner /> : <StressRunner />}</main>;
}

function FunctionalRunner() {
  const tree = useQuery({ queryKey: ["centinel", "tree"], queryFn: ({ signal }) => api.get<TestTree>("/api/admin/centinel/tree", signal), staleTime: 5 * 60_000 });
  const status = useQuery({ queryKey: ["centinel", "status"], queryFn: ({ signal }) => api.get<RunnerStatus>("/api/admin/centinel/status", signal), refetchInterval: (query) => query.state.data?.status === "running" ? 3000 : false });
  const history = useQuery({ queryKey: ["centinel", "history"], queryFn: ({ signal }) => api.get<HistoryItem[]>("/api/admin/centinel/history", signal) });
  const refetchStatus = status.refetch;
  const refetchHistory = history.refetch;
  const [selection, setSelection] = useState<Set<string> | null>(null); const [runId, setRunId] = useState<string | null>(null); const [events, setEvents] = useState<TestEvent[]>([]); const [summary, setSummary] = useState<TestSummary | null>(null); const [filter, setFilter] = useState<"all" | "failed" | "passed" | "skipped">("all"); const [showLog, setShowLog] = useState(false); const [treeSearch, setTreeSearch] = useState("");
  const allFiles = useMemo(() => (tree.data?.dirs ?? []).flatMap((directory) => directory.files.map((file) => file.file)), [tree.data]);
  const selectedFiles = useMemo(() => selection ?? new Set(allFiles), [allFiles, selection]); const currentRunId = runId ?? (status.data?.status === "running" ? status.data.run_id ?? null : null); const running = Boolean(currentRunId) && (status.data?.status === "running" || runId !== null);
  const start = useMutation({ mutationFn: ({ target, rerun }: { target: string; rerun: boolean }) => api.post<{ run_id: string; status: string }>("/api/admin/centinel/run", { target, rerun_failed: rerun }), onSuccess: (result) => { setEvents([]); setSummary(null); setRunId(result.run_id); } });
  const abort = useMutation({ mutationFn: () => api.delete("/api/admin/centinel/run"), onSuccess: () => { setRunId(null); void status.refetch(); void history.refetch(); } });
  useEffect(() => {
    if (!currentRunId) return;
    const controller = new AbortController();
    void (async () => {
      try {
        for await (const event of streamEvents<TestEvent>(`/api/admin/centinel/stream/${encodeURIComponent(currentRunId)}`, { signal: controller.signal })) {
          const item = event.data; setEvents((current) => [...current, item]);
          if (item.type === "summary") setSummary(item);
          if (item.type === "done" || item.type === "aborted" || item.type === "error") { setRunId(null); void refetchStatus(); void refetchHistory(); break; }
        }
      } catch (error) { if (!controller.signal.aborted) console.error("Centinel SSE", error); }
    })();
    return () => controller.abort();
  }, [currentRunId, refetchHistory, refetchStatus]);
  const tests = events.filter((event): event is CompletedTestEvent => event.type === "test" && Boolean(event.file && event.name && event.status));
  const groups = useMemo(() => tests.reduce<Map<string, CompletedTestEvent[]>>((result, event) => {
    const group = result.get(event.file) ?? [];
    group.push(event);
    result.set(event.file, group);
    return result;
  }, new Map()), [tests]);
  const pendingFiles = useMemo(() => (tree.data?.dirs ?? []).flatMap((directory) => directory.files).filter((file) => selectedFiles.has(file.file)), [tree.data, selectedFiles]);
  const localSummary = summary ?? tests.reduce<TestSummary>((result, test) => {
    if (test.status === "passed") result.passed = (result.passed ?? 0) + 1;
    else if (test.status === "skipped") result.skipped = (result.skipped ?? 0) + 1;
    else result.failed = (result.failed ?? 0) + 1;
    return result;
  }, {});
  const progress = tests.at(-1)?.progress ?? 0;
  const launch = (rerun = false) => { const files = [...selectedFiles]; const target = files.length === allFiles.length ? "tests/" : files.join(" "); if (target) start.mutate({ target, rerun }); };
  const toggle = (file: string, checked: boolean) => { const next = new Set(selectedFiles); if (checked) next.add(file); else next.delete(file); setSelection(next); };
  return <>{(localSummary.passed !== undefined || localSummary.failed || localSummary.skipped) && <div className="ctn-summary-bar"><span className="ctn-badge passed">✓ {localSummary.passed ?? 0} pasados</span>{Boolean(localSummary.failed) && <span className="ctn-badge failed">✗ {localSummary.failed} fallidos</span>}{Boolean(localSummary.skipped) && <span className="ctn-badge skipped">⊘ {localSummary.skipped} omitidos</span>}<span className="ctn-badge">{tests.length} en total</span></div>}
    <div className="ctn-header-actions"><button id="btn-run" className="btn btn-primary btn-sm" disabled={running || start.isPending || selectedFiles.size === 0} onClick={() => launch(false)}><svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor" style={{ marginRight: 5 }}><path d="M4 2l10 6-10 6V2z" /></svg>Ejecutar</button>{(status.data?.failed_ids?.length ?? 0) > 0 && <button className="btn btn-ghost btn-sm" disabled={running} onClick={() => launch(true)}>Re-run fallidos</button>}{running && <button className="btn btn-danger btn-sm" disabled={abort.isPending} onClick={() => abort.mutate()}>Abortar</button>}</div>
    {running && <div className="ctn-progress-wrap"><div className="ctn-progress-track"><div className="ctn-progress-bar" style={{ width: `${progress}%` }} /></div><span className="ctn-progress-text">{progress}%</span><span className="ctn-progress-current">{tests.at(-1)?.file}</span></div>}
    {(tree.error || status.error || start.error || abort.error) && <p className="form-error">{errorText(tree.error ?? status.error ?? start.error ?? abort.error)}</p>}
    <div className="ctn-layout"><aside className="ctn-tree-panel"><div className="ctn-panel-hdr"><span className="ctn-panel-title">Módulos</span><input type="search" className="ctn-search" placeholder="Filtrar…" value={treeSearch} onChange={(event) => setTreeSearch(event.target.value)} /></div><div className="ctn-tree-body">{tree.isPending ? <div className="ctn-tree-loading">Descubriendo tests…</div> : tree.data?.dirs.filter((directory) => !treeSearch || directory.dir.toLowerCase().includes(treeSearch.toLowerCase()) || directory.files.some((file) => file.file.toLowerCase().includes(treeSearch.toLowerCase()))).map((directory) => <details className="ctn-dir-item" key={directory.dir}><summary className="ctn-dir-hdr"><span className="ctn-dir-name">{directory.dir}</span><span className="ctn-dir-count">{directory.count}</span></summary><div className="ctn-dir-files">{directory.files.map((file) => <label className="ctn-file-row" key={file.file}><input className="ctn-file-cb" type="checkbox" checked={selectedFiles.has(file.file)} onChange={(event) => toggle(file.file, event.target.checked)} /><span className={`ctn-file-dot ${tests.some((test) => test.file === file.file && (test.status === "failed" || test.status === "error")) ? "failed" : tests.some((test) => test.file === file.file && test.status === "passed") ? "passed" : ""}`} /><span className="ctn-file-name" title={file.file}>{file.file.split("/").at(-1)}</span><span className="ctn-file-count">{file.count}</span></label>)}</div></details>)}</div><div className="ctn-tree-footer"><button className="btn btn-ghost btn-xs" onClick={() => setSelection(null)}>Todo</button><button className="btn btn-ghost btn-xs" onClick={() => setSelection(new Set())}>Ninguno</button><span className="ctn-sel-count">{(tree.data?.dirs ?? []).flatMap((directory) => directory.files).filter((file) => selectedFiles.has(file.file)).reduce((total, file) => total + file.count, 0)}/{(tree.data?.dirs ?? []).reduce((total, directory) => total + directory.count, 0)}</span></div></aside>
      <section className="ctn-results-panel"><div className="ctn-panel-hdr"><span className="ctn-panel-title">Resultados</span><div className="ctn-filter-tabs">{(["all", "failed", "passed", "skipped"] as const).map((value) => <button key={value} className={`ctn-filter-tab${filter === value ? " active" : ""}`} onClick={() => setFilter(value)}>{{ all: "Todos", failed: "Fallidos", passed: "Pasados", skipped: "Omitidos" }[value]}</button>)}</div><button className="btn-icon-log" title="Ver log" onClick={() => setShowLog((value) => !value)}>◉</button></div>{showLog ? <pre className="ctn-log-pane" style={{ display: "block" }}>{events.map((event) => event.type === "test" ? `${event.file}::${event.name} ${event.status} [${event.progress}%]${event.traceback ? `\n${event.traceback}` : ""}` : event.type === "started" ? `=== ${event.target} ===` : event.type === "error" ? `ERROR: ${event.message}` : "").filter(Boolean).join("\n")}</pre> : <div className="ctn-results-body">{groups.size ? [...groups.entries()].map(([file, fileTests]) => { const visible = fileTests.filter((test) => filter === "all" || (filter === "failed" ? test.status === "failed" || test.status === "error" : test.status === filter)); return visible.length ? <details className="ctn-file-section" open key={file}><summary className="ctn-file-sec-hdr"><span className="ctn-file-sec-name">{file}</span><span className="ctn-file-sec-badges"><span className="ctn-sec-badge passed">{fileTests.filter((test) => test.status === "passed").length} ✓</span>{fileTests.some((test) => test.status === "failed" || test.status === "error") && <span className="ctn-sec-badge failed">{fileTests.filter((test) => test.status === "failed" || test.status === "error").length} ✗</span>}</span></summary><div className="ctn-file-sec-body">{visible.map((test) => <div key={test.name}><div className={`ctn-test-row${test.traceback ? " clickable" : ""}`}><span className={`ctn-test-icon ${test.status}`}>{test.status === "passed" ? "✓" : test.status === "skipped" ? "⊘" : "✗"}</span><span className={`ctn-test-name ${test.status}`}>{test.name}</span></div>{test.traceback && <pre className="ctn-traceback open">{test.traceback}</pre>}</div>)}</div></details> : null; }) : pendingFiles.length ? pendingFiles.map((file) => <details className="ctn-file-section" open key={file.file}><summary className="ctn-file-sec-hdr"><span className="ctn-file-sec-name">{file.file}</span><span className="ctn-file-sec-badges"><span className="ctn-sec-badge">Pendiente</span></span></summary></details>) : <div className="ctn-empty-state"><p>{running ? "Ejecutando…" : "Ejecuta los tests para ver los resultados"}</p></div>}</div>}</section></div>
    <div className="ctn-history-section"><div className="ctn-history-title">Historial reciente</div><div className="ctn-history-list">{history.data?.length ? history.data.map((item) => <div className="ctn-history-row" key={item.run_id}><span className={`ctn-history-dot ${item.summary?.failed ? "failed" : item.status}`} /><span className="ctn-history-date">{item.started_at ? new Date(item.started_at * 1000).toLocaleString("es-ES") : "—"}</span><span className="ctn-history-target">{item.target}</span><span className="ctn-history-summary">✓ {item.summary?.passed ?? 0} {item.summary?.failed ? `· ✗ ${item.summary.failed}` : ""}</span><span className="ctn-history-dur">{item.finished_at && item.started_at ? `${(item.finished_at - item.started_at).toFixed(1)}s` : "—"}</span></div>) : <div className="ctn-history-empty">Sin ejecuciones previas</div>}</div></div>
  </>;
}

interface StressTick { type?: string; tick: number; count: number; errors: number; avg_ms: number; p95_ms: number; min_ms: number; max_ms: number; rps: number }
interface StressError { t: number; method: string; path: string; status?: number | null; msg: string; ms: number }
interface StressResult { total?: number; errors?: number; duration_s?: number; rps?: number; avg_ms?: number; min_ms?: number; max_ms?: number; p50_ms?: number; p90_ms?: number; p95_ms?: number; p99_ms?: number }
interface StressStatus { status: "idle" | "running" | "done" | "aborted" | "error"; run_id?: string | null; result?: StressResult; ticks?: StressTick[]; errors?: StressError[] }

function StressRunner() {
  const [path, setPath] = useState("RANDOM"); const [method, setMethod] = useState("GET"); const [users, setUsers] = useState(10); const [duration, setDuration] = useState(30); const [rampUp, setRampUp] = useState(0); const [timeout, setTimeoutValue] = useState(10); const [fluctuate, setFluctuate] = useState(false);
  const status = useQuery({ queryKey: ["centinel", "stress"], queryFn: ({ signal }) => api.get<StressStatus>("/api/admin/centinel/stress/status", signal), refetchInterval: (query) => query.state.data?.status === "running" ? 1000 : 5000 });
  const start = useMutation({ mutationFn: () => api.post("/api/admin/centinel/stress/run", { path, method, users, duration, ramp_up: rampUp, timeout, fluctuate_users: fluctuate }), onSuccess: () => status.refetch() });
  const abort = useMutation({ mutationFn: () => api.delete("/api/admin/centinel/stress/run"), onSuccess: () => status.refetch() });
  const running = status.data?.status === "running"; const result = status.data?.result ?? {}; const ticks = status.data?.ticks ?? []; const errors = status.data?.errors ?? []; const maxTick = Math.max(1, ...ticks.map((tick) => tick.p95_ms));
  const exportCsv = () => { const rows = ["t,count,errors,avg_ms,p95_ms,min_ms,max_ms,rps", ...ticks.map((tick) => [tick.tick, tick.count, tick.errors, tick.avg_ms, tick.p95_ms, tick.min_ms, tick.max_ms, tick.rps].join(","))]; const url = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = `stress-${new Date().toISOString().replaceAll(":", "-")}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <><div className="ctn-header-actions" style={{ marginBottom: 12 }}>{running ? <button className="btn btn-danger btn-sm" disabled={abort.isPending} onClick={() => abort.mutate()}>■ Abortar</button> : <button className="btn btn-primary btn-sm" disabled={start.isPending} onClick={() => start.mutate()}>▶ Iniciar prueba</button>}</div><div className="stress-config-card"><div className="stress-config-grid"><div className="stress-field stress-field--wide"><label className="stress-label">Endpoint</label><select className="stress-select" value={path} onChange={(event) => setPath(event.target.value)}><option value="RANDOM">Random (endpoints mixtos)</option><option value="/api/auth/me">/api/auth/me</option><option value="/api/agents">/api/agents</option><option value="/api/connections">/api/connections</option><option value="/api/skills/private">/api/skills/private</option><option value="/api/knowledge">/api/knowledge</option></select><select className="stress-select" value={method} onChange={(event) => setMethod(event.target.value)}><option>GET</option><option>POST</option><option>DELETE</option><option>RANDOM</option></select></div><div className="stress-field"><label className="stress-label">Usuarios concurrentes</label><div className="stress-slider-row"><input className="stress-slider" type="range" min={1} max={1000} value={users} onChange={(event) => setUsers(Number(event.target.value))} /><span className="stress-val">{users}</span></div><label className="stress-checkbox-row"><input type="checkbox" checked={fluctuate} onChange={(event) => setFluctuate(event.target.checked)} /><span className="stress-checkbox-label">Fluctuar carga</span></label></div><Pills label="Duración" value={duration} values={[10, 30, 60, 300]} suffix="s" onChange={setDuration} /><Pills label="Ramp-up" value={rampUp} values={[0, 5, 10, 30]} suffix="s" onChange={setRampUp} /><Pills label="Timeout / req" value={timeout} values={[2, 3, 10, 30]} suffix="s" onChange={setTimeoutValue} /></div></div>
    {(status.error || start.error || abort.error) && <p className="form-error">{errorText(status.error ?? start.error ?? abort.error)}</p>}
    <div className="stress-chart-card"><div className="stress-chart-header"><span className="stress-chart-title">Tiempo de respuesta en tiempo real</span><span>{ticks.at(-1)?.rps ?? 0} req/s</span></div><div className="stress-chart-wrap" style={{ display: "flex", alignItems: "end", gap: 2, padding: 18 }}>{ticks.length ? ticks.map((tick) => <div key={tick.tick} title={`t=${tick.tick}s avg=${tick.avg_ms}ms p95=${tick.p95_ms}ms`} style={{ flex: 1, minWidth: 2, maxWidth: 18, height: `${Math.max(2, tick.p95_ms / maxTick * 100)}%`, background: tick.errors ? "var(--danger)" : "var(--accent)", opacity: .75 }} />) : <div className="stress-chart-empty"><p>Inicia la prueba para ver la gráfica</p></div>}</div></div>
    {Object.keys(result).length > 0 && <div className="stress-summary-card"><div style={{ display: "flex", justifyContent: "space-between" }}><div className="stress-summary-title">Resultados</div><button className="btn btn-ghost btn-sm" onClick={exportCsv}>Exportar CSV</button></div><div className="stress-summary-grid">{[["Peticiones", result.total], ["Errores", result.errors], ["req/s", result.rps], ["Avg ms", result.avg_ms], ["p50 ms", result.p50_ms], ["p90 ms", result.p90_ms], ["p95 ms", result.p95_ms], ["p99 ms", result.p99_ms], ["Min ms", result.min_ms], ["Max ms", result.max_ms]].map(([label, value]) => <div className="stress-stat" key={label}><span className="stress-stat-val">{value ?? "—"}</span><span className="stress-stat-label">{label}</span></div>)}</div></div>}
    {errors.length > 0 && <div className="stress-errors-card" style={{ display: "block" }}><div className="stress-errors-header"><span className="stress-errors-title">Errores detectados</span><span className="stress-errors-badge">{errors.length}</span></div><div className="stress-errors-wrap"><table className="stress-errors-table"><thead><tr><th>t (s)</th><th>Método</th><th>Endpoint</th><th>Código</th><th>Error</th><th>ms</th></tr></thead><tbody>{errors.map((error, index) => <tr key={`${error.t}-${index}`}><td>{error.t}</td><td>{error.method}</td><td>{error.path}</td><td>{error.status ?? "—"}</td><td>{error.msg}</td><td>{error.ms}</td></tr>)}</tbody></table></div></div>}
  </>;
}

function Pills({ label, value, values, suffix, onChange }: { label: string; value: number; values: number[]; suffix: string; onChange: (value: number) => void }) { return <div className="stress-field"><label className="stress-label">{label}</label><div className="stress-pills">{values.map((item) => <button key={item} className={`stress-pill${value === item ? " active" : ""}`} onClick={() => onChange(item)}>{item === 0 ? "Ninguno" : `${item}${suffix}`}</button>)}</div></div>; }

